trunk/DependencyChecker.Web/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DependencyChecker.Common;
using DependencyChecker.DataProvider.DAL;
using DependencyChecker.DataProvider.Helpers;
using DependencyChecker.Entities.Utils;
using DependencyChecker.WCF;
using DependencyChecker.Web.Authorization;
using DependencyChecker.Web.Models;

namespace DependencyChecker.Web.Controllers
{
    public class MainController : Controller
    {
        protected String BasePath
        {
            get
            {
                var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Cache");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                return path;
            }
        }

        //
        // GET: /Main/

        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult ErrorsList()
        {
            var client = new DependencyCheckerServiceProxy();
            var status = client.GetStatus();
            if (status.State != DependencyCheckerServiceState.Ready)
                return RedirectToAction("Index");
            

            return View();
        }

        public ActionResult Cleanup(Guid id, int gens = 1)
        {
            var client = new DependencyCheckerServiceProxy();
            var scope = client.GetDetails(id);
            var result = client.GetUnusedEntities(id, gens);
            return View(new CleanupModel
            {
                Scope = scope,
                Unused = result
            });
        }

        private void LogAction(string message)
        {
            if (User.Identity.IsAuthenticated)
            {
                LoggerHelper.Log.InfoFormat("User {0} requested {1}", User.Identity.Name, message);
            }
            else
            {
                LoggerHelper.Log.InfoFormat("Anonymous requested {0}", message);
            }
        }

        [HttpGet]
        public JsonResult GetBatches()
        {
            var client = new DependencyCheckerServiceProxy();
            var ents = client.GetBatches();

            return Json(new { result = ents.OrderBy(e => e.Date).ToList() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetBatchEntities(int batchId)
        {
            var client = new DependencyCheckerServiceProxy();
            var ents = client.GetBatchEntities(batchId);

            return Json(new {result = ents.OrderBy(e=>e.Name)}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetEntityErrors(int batchId, string entityName)
        {
            var client = new DependencyCheckerServiceProxy();
            var ents = client.GetEntityErrors(batchId, entityName);

            return Json(new { result = ents.OrderBy(e=>e) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Drillthrough(Guid id, String[] types)
        {
            LogAction(String.Format("drill through with parameters: id = {0}", id));

            var client = new DependencyCheckerServiceProxy();
            var result = client.Drillthrough(id, types);
            var status = client.GetStatus();

            return Json(new { result = result, status = status });
        }

        [HttpPost]
        public JsonResult Search(string name, bool isRegex = false, bool includeBody = false, bool exactSearch = false)
        {
            LogAction(String.Format("search with parameters: name = {0}, regular expression: {1}, in body: {2}, exact: {3}",
                name, isRegex, includeBody, exactSearch));

            if (isRegex)
            {
                try
                {
                    Regex.Match("", name.Trim());
                }
                catch (ArgumentException)
                {
                    throw new ArgumentException("Regular expression is not correct. Please, fix it and try again.");
                }
            }

            var client = new DependencyCheckerServiceProxy();
            var status = client.GetStatus();

            if (String.IsNullOrEmpty(name.Trim()))
            {
                return Json(new { result = new List<Entity>(), status = status });
            }

            var result = client.Search(name.Trim(), isRegex, includeBody, exactSearch).OrderBy(e => e.Name).ToList();

            return Json(new { result = result, status = status });
        }

        [HttpPost]
        public JsonResult GetStatus()
        {
            var client = new DependencyCheckerServiceProxy();
            var result = client.GetStatus();

            return Json(new { status = result });
        }

        [HttpPost]
        public JsonResult GetDatabases()
        {
            var client = new DependencyCheckerServiceProxy();
            var status = client.GetStatus();
            var result = client.GetDatabases().OrderBy(e => e.Name);
            //var result = DatabaseHelpers.GetDatabases().OrderBy(e=>e.Name);
            return Json(new { status = status, result = result.Select(e=>e.Name).ToList() });
        }

        [HttpPost]
        public JsonResult GetDetails(Guid id)
        {
            LogAction(String.Format("object details for: id = {0}", id));

            var client = new DependencyCheckerServiceProxy();
            var result = client.GetDetails(id);
            result.DependsOn = result.DependsOn.OrderBy(e => e.Name).ToList();
            result.UsedBy = result.UsedBy.OrderBy(e => e.Name).ToList();
            var status = client.GetStatus();

            return Json(new { result = result, status = status });
        }

        [HttpGet]
        public FileResult DownloadCleanup(Guid id)
        {
            LogAction(String.Format("cleanup download for: id = {0}", id));

            var client = new DependencyCheckerServiceProxy();
            var status = client.GetStatus();
            var item = client.GetDetails(id);
            var result = client.GetUnusedCleanupScripts(id);

            if (client.GetState() != DependencyCheckerServiceState.Ready.ToString())
            {
                var name = Path.Combine(BasePath, item.Name + ".zip");
                var info = new FileInfo(name);
                using (var writer = info.CreateText())
                {
                    writer.WriteLine("Dependency checker is unavailable. Current status: " + status);
                }
                return File(info.OpenRead(), "text/plain");
            }
            return File(result, "application/zip, application/octet-stream");
        }

        [HttpPost]
        public FileResult DownloadSetCleanup(Guid id, String idStr)
        {
            var ids = idStr.Split(new[] {';'}, StringSplitOptions.RemoveEmptyEntries);
            LogAction(String.Format("download object details for: ids:\r\n{0}", String.Join("\r\n", ids)));

            var client = new DependencyCheckerServiceProxy();
            var status = client.GetStatus();
            var item = client.GetDetails(id);
            var result = client.GetUnusedCleanupScriptsForSet(id, ids.Select(s => new Guid(s)).ToArray());

            if (client.GetState() != DependencyCheckerServiceState.Ready.ToString())
            {
                var name = Path.Combine(BasePath, item.Name + ".zip");
                var info = new FileInfo(name);
                using (var writer = info.CreateText())
                {
                    writer.WriteLine("Dependency checker is unavailable. Current status: " + status);
                }
                return File(info.OpenRead(), "text/plain");
            }
            return File(result, "application/zip, application/octet-stream");
        }        
        
        [HttpGet]
        public FileResult DownloadDetails(Guid id)
        {
            LogAction(String.Format("download object details for: id = {0}", id));

            var client = new DependencyCheckerServiceProxy();
            var status = client.GetStatus();

            var result = client.PrintEntity(id);

            result = Regex.Replace(result, @"([ \t]+)?(?<var>\$(USER|PWD))([ \t]+)?=([ \t]+)?(?<value>('[^']+'|""[^""]+""))([ \t]+)?;([ \t]+)?", 
                String.Empty, RegexOptions.IgnoreCase | RegexOptions.Multiline);

            var name = Path.Combine(BasePath, id + ".txt");
            var info = new FileInfo(name);
            if (info.Exists)
                return File(info.OpenRead(), "text/plain", info.Name + ".txt");


            if (client.GetState() != DependencyCheckerServiceState.Ready.ToString())
            {
                using (var writer = info.CreateText())
                {
                    writer.WriteLine("Dependency checker is unavailable. Current status: " + status);
                }
            }
            else
            {
                using (var writer = info.CreateText())
                {
                    writer.WriteLine(result);
                }
            }
            return File(info.OpenRead(), "text/plain", info.Name + ".txt");
        }

        /// <summary>
        /// Controller method for exporting Item's dependents information
        /// </summary>
        /// <param name="id">Entity id</param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ExportAll(Guid id)
        {
            LogAction(String.Format("download export all details for: id = {0}", id));


trunk/DependencyChecker.Web/Views/Main/Cleanup.cshtml
@using System.Text.RegularExpressions
@using DependencyChecker.Entities
@using DependencyChecker.Entities.Utils
@model DependencyChecker.Web.Models.CleanupModel

@{
    ViewBag.Title = "Dependency checker tool";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    var types = Model.Unused.GroupBy(e => e.Type);
    var numberOfItems = Model.Unused.Count(r => !r.Name.Contains("~IGNORE~"));
}

<div class="container">
    <h1 class="text-muted">Dependency checker
        <label class="small" style="color: #428bca; top: -10px; display: inline-block; position: relative;">Beta</label></h1>
    <h3>
        <label class="label-default" style="color: white;" id="status"></label>
    </h3>
    <div id="progress" class="progress">
    </div>
    
    <h4>Cleanup script generation for: @(Model.Scope.Type.ToLowerInvariant()) '@(Model.Scope.Name)'</h4>
    <div class="btn-group" data-toggle="buttons" id="typeFilter">
        @foreach (var type in types)
        {
            <label class="btn btn-default active">
                <input type="checkbox" checked="checked" name="@(type.Key)">@(type.Key) &nbsp;<span class="badge pull-right">@(type.Count())</span></label>
        }
    </div>
    <div class="pull-right form-inline">
    @using (Html.BeginForm("DownloadSetCleanup", "Main", FormMethod.Post))
    {
        <input type="hidden" id="id" name="id" value="@(Model.Scope.Id)" />
        <input type="hidden" id="idStr" name="idStr" value="" />
        <button type="submit" id="download" class="btn btn-primary pull-right" role="button">Download cleanup</button>
    }
    </div>
    <div>
        <span>Shown results: <span id="resultsNum">@(Model.Unused.Count)</span></span>&nbsp;  <label><input type="checkbox" id="showIgnored" /> Show ignored</label>

    </div>
    <div>
        
    </div>
    @if (numberOfItems > 50)
    {
        <ul class="pagination">
          @*<li><a href="#">&laquo;</a></li>*@
        @for (var i = 1; i < numberOfItems / 50 + 1; i++)
        {
            <li style="cursor: pointer;" @(Html.Raw(i == 1 ? "class=\"active\"" : String.Empty))><a data-page="@(i)">@(i)</a></li>
        }        
          @*<li><a href="#">&raquo;</a></li>*@
        </ul>
    }

    <ul class="list-group" id="results">
        @{
            var results = 0;
        }
        @foreach (var result in Model.Unused)
        {
            EntityType type;
            var name =
                Regex.Replace(result.Name,
                    (result.Type == "BatchFile" || result.Type == "PerlScript" || result.Type == "Executable") ?
                        @"(\\|\/)([^\/^\\]+)$" : @"(\.|\/)([^\.^\/]+)$",
                    "$1<b>$2</b>");
            if (!Enum.TryParse(result.Type, out type))
            {
                type = EntityType.Unresolved;
            }
            <li class="list-group-item res @(result.Name.Contains("~IGNORE~") || results++ > 50 ? "hide" : String.Empty)" name="@(result.Type)">
                <div class="form-group">
                    <input type="hidden" class="id" value="@(result.Id)" />
                    <button type="button" class="btn-default btn-xs">+</button>
                    <span class="label t @(type.GetStyle())">@(result.Type)</span>&nbsp;&nbsp;<span class="n">@(Html.Raw(name))</span>
                    <div class="pull-right">
                        <a href="@Url.Action("DownloadDetails", new { id = result.Id })" target="_blank">download</a>
                    </div>
                </div>
            </li>
        }
    </ul>
    
    @if (numberOfItems > 50)
    {
        <ul class="pagination">
          @*<li><a href="#">&laquo;</a></li>*@
        @for (var i = 1; i < numberOfItems / 50 + 1; i++)
        {
            <li style="cursor: pointer;" @(Html.Raw(i == 1 ? "class=\"active\"" : String.Empty))><a data-page="@(i)">@(i)</a></li>
        }        
          @*<li><a href="#">&raquo;</a></li>*@
        </ul>
    }

    <script type="text/javascript">
        var pageNum = 0;
        $(document).ready(function () {
            $(".list-group-item").each(function() {
                $(this).find('button').click(function () {
                    var element = $(this).parent().parent();
                    LoadEntity(element);
                });
            });
            $(".pagination a").on('click', function () {
                pageNum = parseInt($(this).data("page")) - 1;
                $(".pagination li.active").removeClass("active");
                $(this).parent().addClass("active");
                filterResults(pageNum);
            });

            buildDownload();
        });

        $("#typeFilter input").change(function () {
            pageNum = 0;
            filterResults(pageNum);
        });

        $("#showIgnored").change(function () {
            pageNum = 0;
            filterResults(pageNum);
        });

        function filterResults(page) {
            var filters = new Array();
            $("#typeFilter input:checked").each(function() {
                filters.push($(this).attr("name"));
            });

            var showIgnored = $("#showIgnored").prop("checked");

            var num = 0;
            $("#results li").each(function() {
                var show = filters.indexOf($(this).attr("name")) >= 0;

                if (!showIgnored && $(this).find(".n").text().indexOf("~IGNORE~") > 0) {
                    show = false;
                }

                if (show) {
                    if (page == Math.floor(num / 50)) {
                        $(this).removeClass("hide");
                        $(this).show();
                    } else {
                        $(this).hide();
                    }
                    num++;
                } else {
                    $(this).hide();
                }
            });

            $("#resultsNum").html(num);

            $(".pagination li").remove();
            num = Math.floor(num / 50) + 1;
            for (var i = 1; i <= num; i++) {
                $(".pagination").append('<li ' + (page == i - 1 ? ' class="active"' : '') + ' style="cursor: pointer;"><a data-page="' + i + '">' + i + '</a></li>');
            }

            $(".pagination a").on('click', function () {
                pageNum = parseInt($(this).data("page")) - 1;
                $(".pagination li.active").removeClass("active");
                $(this).parent().addClass("active");
                filterResults(pageNum);
            });
            buildDownload();
        }

        function buildDownload() {
            var str = "";
            $("#results li:visible").each(function() {
                str += $(this).find(".id").val() + ";";
            });
            $("#idStr").val(str);
        }
    </script>
</div>



trunk/DependencyChecker.Web/Views/Main/Index.cshtml
@using DependencyChecker.Entities
@using DependencyChecker.Web.Authorization
@model dynamic

@{
    ViewBag.Title = "Dependency checker tool";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    var drillDownTypes = new List<EntityType>
    {
        EntityType.Report,
        EntityType.Job,
        EntityType.Folder,
        EntityType.P1TCView
    }.Select(t => t.ToString()).ToList();
}

@section HeaderButtons{
    


    <h3>
        <label class="label-default" style="color: white;" id="status"></label>
    </h3>
    <div id="progress" class="progress">
    </div>
    <fieldset id="searchArea">
        <div class="input-group">
            <input type="text" class="form-control" id="searchQuery">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default" id="defaultSearch">Search</button>
                @*                    <button tabindex="-1" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li><a id="simpleSearch" href="#">Simple search</a></li>
                        <li><a id="regexSearch" href="#">Search regular expression</a></li>
                        <li><a id="drillthroughSearch" href="#">Drill through</a></li>
                    </ul>*@
            </div>
        </div>
        <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-default">
                <input type="checkbox" id="useRegularExpression">
                Enable regular expression
            </label>
            <label class="btn btn-default">
                <input type="checkbox" id="exactSearch">
                Exact search
            </label>
            <label class="btn btn-default">
                <input type="checkbox" id="useDefinition">
                Search in definition
            </label>
        </div>
        <div class="btn-group" role="group" data-toggle="buttons">
            <label class="btn btn-default">
                <input type="checkbox" id="useDrillThrough">
                Drill down
            </label>
            <button type="button" class="btn btn-default dropdown-toggle" aria-haspopup="true" data-toggle="dropdown" aria-expanded="false">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" id="drillDownFilter">
                @foreach (var type in Enum.GetNames(typeof(EntityType)).Where(n => n != "Unresolved"))
                {
                    <li class="checkbox">
                        <label class="small" data-value="@(type)" tabIndex="-1">
                            <input type="checkbox" @Html.Raw(drillDownTypes.Contains(type) ? "checked=\"checked\" " : String.Empty)>
                            @(type)
                        </label>
                    </li>
                }
            </ul>
        </div>
        <div style="display: none;" class="btn-group" role="group" data-toggle="buttons" id="db-list-button">

            <button type="button" class="btn btn-default dropdown-toggle" aria-haspopup="true" data-toggle="dropdown" aria-expanded="false">
                <span class="">Databases</span>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" id="databaseFetcher"></ul>

        </div>
        <div style="display: none;" class="btn-group" id="errors-list">
            <a href="@Url.Action("ErrorsList", "Main")">Errors list</a>
        </div>
    </fieldset>
}

<ul class="list-group" id="results">
    <h2></h2>
</ul>


<script type="text/javascript">
    var _drillDownOptions = [@Html.Raw(String.Join(",", drillDownTypes.Select(t => "\""+ t + "\"")))];
    $('#drillDownFilter label').on('click', function (event) {
        var $target = $(event.currentTarget),
            val = $target.attr('data-value'),
            $inp = $target.find('input'),
            idx;

        if ((idx = _drillDownOptions.indexOf(val)) > -1) {
            _drillDownOptions.splice(idx, 1);
            setTimeout(function () { $inp.prop('checked', false) }, 0);
        } else {
            _drillDownOptions.push(val);
            setTimeout(function () { $inp.prop('checked', true) }, 0);
        }
        $(event.target).blur();
        return false;
    });
    $("#drillDownFilter").click(function(e) {
        e.originalEvent.stopImmediatePropagation();
        e.originalEvent.stopPropagation();
        e.originalEvent.preventDefault();
    });
    $("#databaseFetcher").click(function (e) {
        e.originalEvent.stopImmediatePropagation();
        e.originalEvent.stopPropagation();
        e.originalEvent.preventDefault();
    });
    //$("#drillDownFilter .checkbox label").click(function(e) {
    //    if ($(this).find("input:checked").length === 0) {
    //        $(this).find("input").attr("checked", "checked");
    //    } else {
    //        $(this).find("input").removeAttr("checked");
    //    }
    //});
    $('#defaultSearch').click(function () {
        var useRegex = ($("#useRegularExpression:checked").length === 1);
        var useBody = ($("#useDefinition:checked").length === 1);
        var exactSearch = ($("#exactSearch:checked").length === 1);

        return requestService('Search', function (data) {
            window.searchResult = data;
            $("#results").html("");
        }, true, { name: $("#searchQuery").val(), isRegex: useRegex, includeBody: useBody, exactSearch: exactSearch }).then(function () {
            window.searchResult.map(function (entity) {
                return ShowEntity($("#results"), entity, $("#searchQuery").val());
            });
        });
    });

    $("#searchQuery").keyup(function (e) {
        if (e.originalEvent.keyCode == 13) {
            $('#defaultSearch').click();
        }
    });

    $('#searchRegex').click();
    $('#showAdvanced').click();
</script>


