trunk/DependencyChecker.Web/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DependencyChecker.DataProvider.Helpers;
using DependencyChecker.Web.Authorization;
using System.Data.Entity;
using DependencyChecker.Common;

namespace DependencyChecker.Web.Controllers
{
    //[AuthorizeRoles("Administrator")]
    public class ControlPanelController : Controller
    {
        //
        // GET: /ControlPanel/

        public ActionResult SPA()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            var users = UserManager.GetAllUsers();

            return View(users);
        }

        
        public ActionResult ExceptionLog()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllUsers()
        {
            return Json(UserManager.GetAllUsers(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult CheckUserExistence(string username)
        {
            return Json(UserManager.CheckUserExistence(username), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public void AddNewAdministrator(string username)
        {
            if (!UserManager.CheckUserExistence(username))
            {
                return;
            }
            else
            {
                UserManager.AddAdministrator(username);
            }
        }

        [HttpPost]
        public void RemoveUser(string username)
        {

            UserManager.Remove(username);
        }

        [HttpGet]
        public JsonResult GetBatches(string from = null, string to = null)
        {
            var client = new DependencyCheckerServiceProxy();
            List<Common.Batch> ents = null;
            if (from == null || to == null)
            {
                ents = client.GetBatches();
            }
            else
            {
                try
                {
                    var fromDate = DateTime.Parse(from);
                    var toDate = DateTime.Parse(to);

                    ents = client.GetBatches(fromDate, toDate);
                }
                catch (Exception e)
                {
                    LoggerHelper.Log.Error("Couldn't parse date. Provide ISO format, please.", e);
                    throw e;
                }
                
            }
            

            return Json(new { result = ents.OrderBy(e => e.Date).ToList() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        
        public JsonResult GetBatchExceptions(int batchId)
        {
            var client = new DependencyCheckerServiceProxy();
            var ents = client.GetBatchExceptions(batchId);

            return Json(new { result = ents.OrderBy(e => e.Level).ThenBy(e => e.Date).ToList() }, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult Restart()
        {
            var client = new DependencyCheckerServiceProxy();
            client.RestartService();
            return RedirectToAction("Index", "Main");
        }
    }
}

trunk/DependencyChecker.Web/Views/ControlPanel/ExceptionLog.cshtml
@{
    ViewBag.Title = "Exception Log";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@section HeaderButtons{
    <div id="search-container">
        <span class="text-muted picker-label">From date:</span>
        <div class='input-group date' id='from-date-picker'>
            <input type='text' class="form-control" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <span class="text-muted picker-label">To:</span>
        <div class='input-group date' id='to-date-picker'>
            <input type='text' class="form-control" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <div class="btn-group batch-btn-group">
            <button type="button" class="btn btn-default" id="search-by-date">Search</button>
            <button type="button" class="btn btn-default" id="show-all">Show all</button>
        </div>
        <span id="date-error" class="text-muted picker-label" style="display: none;">Error</span>
    </div>
}

<ul class="list-group" id="results" style="margin-top: 20px;"></ul>

<script type="text/javascript">

    DC.ControlPanel.ExceptionLog.init();

</script>

trunk/DependencyChecker.Web/Views/ControlPanel/Index.cshtml
@{
    ViewBag.Title = "Control panel";
    Layout = "~/Views/Shared/_MainLayoutStatic.cshtml";
}

<div id="controlPanelMenu">
    <h2 style="margin-bottom: 35px; color: #428bca; margin-top: 5px;">Control panel</h2>
    <div class="options">
        <div class="column" style="width: 49%;">
            <div class="row">
                <a href="@Url.Action("Users", "ControlPanel")">
                    <div>
                        <img src="@Url.Content("~/Content/images/users.png")">
                    </div>
                    <span class="text-muted" style="">Users management</span>
                </a>
            </div>
            <div class="row">
                <a href="@Url.Action("ExceptionLog", "ControlPanel")">
                    <div>
                        <img src="@Url.Content("~/Content/images/error.png")">
                    </div>
                    <span class="text-muted" style="">Exception log</span>
                </a>
            </div>
        </div>
        <div class="column" style="width: 49%;">
            <div class="row">
                <a id="restartSvcBtn" href="@Url.Action("Restart", "ControlPanel")">
                    <div class="caution">
                        <img src="@Url.Content("~/Content/images/refresh.png")">
                    </div>
                    <span class="text-muted" style="">Restart service</span>
                </a>
            </div>
        </div>
    </div>
    
</div>

<script type="text/javascript">
    DC.ControlPanel.Home.init();
</script>

trunk/DependencyChecker.Web/Views/ControlPanel/SPA.cshtml
@using DependencyChecker.Web.Authorization
@{
    ViewBag.Title = "SPA";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="@Url.Content("~/Content/images/favicon.ico")" rel="Shortcut Icon" type="image/x-icon" />

    <title>@(ViewBag.Title)</title>

    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap-datetimepicker.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/dataart-dc.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/jBox.css")" rel="stylesheet">

    <script src="@Url.Content("~/Scripts/jquery-2.1.1.min.js")"> </script>
    <script src="@Url.Content("~/Scripts/moment.min.js")"> </script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"> </script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.min.js")"> </script>
    <script src="@Url.Content("~/Scripts/jBox.min.js")"> </script>
    <script src="@Url.Content("~/Scripts/react.js")"> </script>
    <script src="@Url.Content("~/Scripts/react-dom.js")"> </script>
    <script src="@Url.Content("~/Scripts/react-router.min.js")"> </script>
    <script src="@Url.Content("~/Scripts/da-control-panel.js")"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <style>
        div#header {
            position: static;
        }
    </style>
        <div id="root"></div>


    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="Please wait" aria-hidden="true" id="loadingModal">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Please wait</h4>
                </div>
                <div class="modal-body">
                    Loading content...

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="Copy text" aria-hidden="true" id="copyTextModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Text copy</h4>
                </div>
                <div class="modal-body">
                    <textarea class="form-control" rows="30" cols="" id="copyData"></textarea>
                </div>
            </div>
        </div>
    </div>
    <script src="@Url.Content("~/Scripts/cpanel-users.jsx")"></script>
    <script src="@Url.Content("~/Scripts/app.jsx")"></script>

</body>
</html>

trunk/DependencyChecker.Web/Views/ControlPanel/Users.cshtml
@model IEnumerable<DependencyChecker.Web.Models.AdUser>
@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_MainLayoutStatic.cshtml";
}

<div id="usersList">

    <h2 style="margin-bottom: 35px; color: #428bca; margin-top: 5px;">Users management</h2>

    <div id="userManagement">
        
    </div>
</div>
<div id="addNewUserModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add new administrator</h4>
            </div>
            <div class="modal-body">
                
                    <span style="display: block; margin-bottom: 10px;">Logon name (username without domain):</span>
                    <div class="input-group">
                        <input id="userNameInput" class="form-control" style="display: inline-block" type="text" />
                        <div class="input-group-btn">
                            <button  class="btn btn-default" id="checkUser">Check existence</button>
                        </div>
                    </div>
                
            </div>
            <div class="modal-footer">
                <button id="addNewUserBtn" style="width: 100px;" type="button" class="btn btn-default">Add</button>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">

    DC.ControlPanel.Users.init();

</script>

<script src="@Url.Content("~/Scripts/cpanel-users.jsx")"></script>